window.onload=function(){
	var biaozhun=document.getElementById('biaozhun');
	var kexue=document.getElementById('kexue');
	biaozhun.onclick=function(){
		kexue.style.background='#fff';
		kexue.style.color='#000';
		this.style.background='green';
		this.style.color='#fff';
		screen.style.display='block';
		screen2.style.display='none';
		xs=xianshi;
	};
	kexue.onclick=function(){
		biaozhun.style.background='#fff';
		biaozhun.style.color='#000';
		this.style.background='green';
		this.style.color='#fff';
		screen2.style.display='block';
		screen.style.display='none';
		xs=xianshi2;
	};
	var 
	screen=document.getElementById('screen'),
	screen2=document.getElementById('screen2'),
	button=document.getElementsByClassName('button'),
	button2=document.getElementsByClassName('button2');
	for(var i=0;i<button.length;i++){
		button[i].onmousedown=function(){
			this.style.boxShadow='0 0 10px black inset';
		};
		button[i].onmouseup=function(){
			this.style.boxShadow='';
		};
	}
	for(var i=0;i<button2.length;i++){
		button2[i].onmousedown=function(){
			this.style.boxShadow='0 0 10px black inset';
		};
		button2[i].onmouseup=function(){
			this.style.boxShadow='';
		};
	}
	var 
	xianshi=document.getElementById('xianshi'),
	xianshi2=document.getElementById('xianshi2');
	ops=document.getElementsByClassName('oprator'),
	nums=document.getElementsByClassName('num'),
	equl=document.getElementById('denghao');
	var fir=sec=yunsuanfu='',kk,k1,k2,k3,ll=0,xs=xianshi;
	for(var i=0;i<nums.length;i++){
		nums[i].onclick=function(){
			if(k1){
				return;
			}
			if(yunsuanfu==''){
				if(this.innerHTML=='.'&&fir.indexOf('.')!=-1){
					return;
				}
				if(kk){
					fir='';
					kk=false;
				}
				xs.innerHTML='';
				fir+=this.innerHTML;
				xs.innerHTML=fir;
			}else{
				if(this.innerHTML=='.'&&sec.indexOf('.')!=-1){
					return;
				}
				if(fir!=''&&yunsuanfu!='+/-'){
					sec+=this.innerHTML;
					xs.innerHTML=fir+yunsuanfu+sec;
				}else{
					fir+=this.innerHTML;
					xs.innerHTML=fir;
					yunsuanfu='';
				}
			}
		};
	}
	for(var i=0;i<ops.length;i++){
		ops[i].onclick=function(){
			if(fir==''){return};
			yunsuanfu=this.innerHTML.trim();
			if(yunsuanfu=='AC'){
				xs.innerHTML='0';
				fir=sec=yunsuanfu='';
				return;
			}
			if(yunsuanfu=='+/-'){
				fir=Number(fir)*(-1);
				yunsuanfu='';
				xs.innerHTML=fir;
				return;
			}
			if(yunsuanfu=='mr'){
				k1=true;
				ll=Number(fir);
				return;		
			}
			if(yunsuanfu=='m+'){
				if(k1){
					ll+=Number(fir);
					xs.innerHTML=ll;
				}
				return;
			}
			if(yunsuanfu=='m-'){
				if(k1){
					ll=Number(xs.innerHTML);
					ll-=Number(fir);
					xs.innerHTML=ll;
				}
				return;
			}
			if(yunsuanfu=='mc'){
				if(k1){
					xs.innerHTML=0;
					fir='';
					ll=0;
					k1=false;
				}
				k1=false;
				return;
			}
			xs.innerHTML=fir+yunsuanfu;
			sec='';
		};
	}
	equl.onclick=function(){
		if(yunsuanfu=='+'){
			equl=Number(fir)+Number(sec);
		}
		if(yunsuanfu=='-'){
			equl=Number(fir)-Number(sec);
		}
		if(yunsuanfu=='×'){
			equl=Number(fir)*Number(sec);
		}
		if(yunsuanfu=='÷'){
			equl=Number(fir)/Number(sec);
		}
		if(yunsuanfu!=''){
			if(equl>99999999){
				equl=equl.toPrecision(3);
			}
			console.log(equl);
			xs.innerHTML=fir=equl;
			sec=yunsuanfu='';			
			kk=true;
		}else{
			xs.innerHTML=fir;
		}
	};
	document.onmousedown=function(e){
		e.preventDefault();
	};
};